; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rymcu-esp32-devkitc]
platform = espressif32                              ; 
board = rymcu-esp32-devkitc
framework = arduino, espidf
monitor_speed = 115200
board_build.filesystem = littlefs
monitor_filters = log2file, esp32_exception_decoder
board_build.partitions = partitions.csv
lib_deps = 
    esp32async/ESPAsyncWebServer @ ^3.12.0
    bblanchon/ArduinoJson @ ^7.4.3
    lennarthennigs/ESP Telnet @ ^2.3.0
